2018-09-21 00:07:10,343 [1] INFO  SkieerWeb - RefundJob starting.
2018-09-21 00:07:10,343 [12] INFO  SkieerWeb - RefundJob checking.
2018-09-21 00:07:10,343 [12] INFO  SkieerWeb - IsEnabledRefund = False
2018-09-21 00:07:10,343 [12] INFO  SkieerWeb - RefundJob waiting 30 minutes.
2018-09-21 05:27:11,609 [1] INFO  SkieerWeb - RefundJob starting.
2018-09-21 05:27:11,609 [12] INFO  SkieerWeb - RefundJob checking.
2018-09-21 05:27:11,609 [12] INFO  SkieerWeb - IsEnabledRefund = False
2018-09-21 05:27:11,609 [12] INFO  SkieerWeb - RefundJob waiting 30 minutes.
2018-09-21 07:10:17,468 [1] INFO  SkieerWeb - RefundJob starting.
2018-09-21 07:10:17,484 [12] INFO  SkieerWeb - RefundJob checking.
2018-09-21 07:10:17,484 [12] INFO  SkieerWeb - IsEnabledRefund = False
2018-09-21 07:10:17,484 [12] INFO  SkieerWeb - RefundJob waiting 30 minutes.
2018-09-21 14:30:23,843 [1] INFO  SkieerWeb - RefundJob starting.
2018-09-21 14:30:23,843 [12] INFO  SkieerWeb - RefundJob checking.
2018-09-21 14:30:23,843 [12] INFO  SkieerWeb - IsEnabledRefund = False
2018-09-21 14:30:23,843 [12] INFO  SkieerWeb - RefundJob waiting 30 minutes.
2018-09-21 18:39:34,562 [1] INFO  SkieerWeb - RefundJob starting.
2018-09-21 18:39:34,562 [12] INFO  SkieerWeb - RefundJob checking.
2018-09-21 18:39:34,562 [12] INFO  SkieerWeb - IsEnabledRefund = False
2018-09-21 18:39:34,562 [12] INFO  SkieerWeb - RefundJob waiting 30 minutes.
2018-09-21 18:39:36,453 [10] INFO  SkieerWeb - [Braintree Webhook Received 2018/9/21 10:39:34] | Kind: subscription_charged_successfully
2018-09-21 18:39:57,656 [10] ERROR SkieerWeb - GetAvailableCoupon Error. UserId:55031c79-600e-4167-b913-a584ee0fbdb0
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 101.200.193.134:9002
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetResponse()
   在 Octoparse.Web.HttpHelper.RESTFullRequest(RequestType method, String url, Object bodyContent, String authorization, String contentType)
   在 Octoparse.Web.HttpHelper.Get[T](String url)
   在 Octoparse.Web.Controllers.SubscribeController.GetAvailableCoupon(String userId, PlanType newPlanType, Decimal newPrice, Decimal nowBillingAmount)
2018-09-21 18:39:58,796 [10] ERROR SkieerWeb - Process Error.SubscriptionId:c0ac9f7f-43e4-458e-8dd3-7cc44848257f,PaymentNo:c9eq9vhz
System.ServiceModel.EndpointNotFoundException: 没有终结点在侦听可以接受消息的 http://192.168.0.103:8012/ShareService。这通常是由于不正确的地址或者 SOAP 操作导致的。如果存在此情况，请参见 InnerException 以了解详细信息。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.0.103:8012
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   在 System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Octoparse.Web.OctopusShareService.IOctopusShareService.GetAccount(String userId)
   在 Octoparse.Web.Controllers.SubscribeController.BtHandler()
